pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_commits:
  files:
  - '**/*.md'
  - '.Assets/**/*.*'
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: normal
  project: $(SOLUTION)
after_build:
- ps: "$files = get-childitem -recurse -Filter *.nuspec\nforeach ($file in $files)\n{\n     $nuspec = $file.FullName\n     Write-Host(\"Packing \" + $nuspec + \" package\")\n     nuget pack $nuspec -version $env:APPVEYOR_BUILD_VERSION -OutputDirectory \"_Artifacts\"\n}"
artifacts:
- path: _Artifacts\**\*.nupkg
