version: 1.0.{build}
branches:
  only:
  - $(BRANCH)
image: Visual Studio 2019
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    dotnet restore
    
    nuget restore
build:
  verbosity: minimal
artifacts:
- path: '*\bin\*\*.nupkg'
